### ISSUE TITLE
npx playwright testで起動するとデータの準備が終わらない

### ISSUE THREAD

**Issue by so-c** [so-c/voicevox#4]
https://github.com/so-c/voicevox/blob/9cb02cd6fb8c1bbbcb0c730aac9ec45e82267dd0/tests/e2e/example.spec.ts#L10 はパスするので、documentloaded 状態には遷移している

electron:serveでは動くので`.env`に指定している環境変数が見えていない？

**Comment by so-c** [comment]
テストコードで pause() させてREST `127.0.0.1:50021/docs` にブラウザで接続を試みると、ERR_CONNECTION_REFUSED。起動はしているけれど接続不能になっている模様

electron:serveで動かしたときは接続可能

**Comment by so-c** [comment]
仮説：[Security | Vue CLI Plugin Electron Builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#loading-local-images-resources) ローカルリソースのアクセスにひっかかる？

**Comment by Hiroshiba** [comment]
僕も見てみました！production環境になってしまうことが根本の原因っぽいです。

そもそも.envが読み込まれないのが問題になっています。
.envはelectron起動後にここで読まれます。
https://github.com/VOICEVOX/voicevox/blob/d708b4c340970fc54ed72c532be951579b299aee/src/background.ts#L84-L94

`isDevelopment`で分岐していますが、logを取ってみるとこれがfalseになっていました。
`appDirPath`は`./node_modules/electron/dist`辺りの頓珍漢なところを指すので、.envが見つからずに.envが読めないということが問題っぽいです。
これはビルド時だと嬉しいのですが、開発時はisDevelopment==trueになってほしい感じです。

なぜisDevelopmentがfalseになってるかというと、NODE_ENVがproductionになっているためでした。
https://github.com/VOICEVOX/voicevox/blob/d708b4c340970fc54ed72c532be951579b299aee/src/background.ts#L57

NODE_ENVがdevelopmentとかtestになればいいのですが、その方法がわかりませんでした･･･。
`testWithPlaywright`関数のoptionsのmodeがそれっぽいのですが、ここを変えてもNODE_ENVは変わりませんでした。

ところで、コンソールでelectronのログを見る方法とかご存知でしょうか。。
`%appdata%/voicevox/logs` に出力されたログを眺めていますが、ちょっと不便で･･･。

**Comment by so-c** [comment]
[testWithPlaywrightのソース](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/dc4a629daf34716eb19fcc9da8b88d94e2c5c3b1/lib/testWithPlaywright.js#L20)と、[Modes and Environment Variables | Vue CLI](https://cli.vuejs.org/guide/mode-and-env.html#modes)を見ると、Hiroshibaさんの言う通り、`testWithPlaywright`のoptionsのmodeのように私も思います。

[両方でテストする](https://github.com/so-c/voicevox/commit/3f005269388d00a4b1951dacda2db8a98ce1319f)と挙動が変わるのが気になります。ProductionだとUIができるが、DevelopmentだとUIも出ずエラーログが残る（私も不便です、、、良い方法見つけたら、、、）。

envが読み込めればよいので、以下もうちょっと当たってみます
* Electronの実効プロセスに渡すものであれば、[こちらのenv](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/dc4a629daf34716eb19fcc9da8b88d94e2c5c3b1/lib/testWithPlaywright.js#L45)にNODE_ENVを仕込んだ方が？
* Electron.launchのオプションもちゃんと見る
* とりあえず.envを頓珍漢なところに置いたら動くのか？（実は別の原因の可能性がないのか

**Comment by so-c** [comment]
これだけやって逐一確認しても`NODE_ENV`が流れて行かず`isDevelopment`が`false`のまま

1. テストコード実行前にシェルで環境変数 `$env:NODE_ENV="deployment"`
2. `testWithPlaywright({mode: "development"})`で`electron:serve`のmode指定
3. 環境変数に設定したので`process.env`経由で`electron.launch(launchOptions)`に`NODE_ENV`が含まれているのを確認

**Comment by so-c** [comment]
Vuex.spec.tsの下記を見てテストコードで`dotenv.config()`
```typescript
const isDevelopment = process.env.NODE_ENV == "development";
```
`mode: "production"` (この値がデフォルトなので指定なしでもよいはず) でデータ準備状態を超えるところまで確認
